import { Content, UserStats, GrowthData, WeeklyRegistrationData, AdminUser, Reward, Broadcast } from "./types"

export const initialContents: Content[] = [
    // From Admin Content (Published)
    {
        id: "1",
        type: "video",
        title: "消えゆく集落、再生の灯火 - 限界集落からの逆転劇",
        description: "人口わずか12人の山間集落が、外部人材との協働でいかにして復活を遂げたのか。3年間の密着取材が明かす、地方創生の真実。",
        status: "published",
        publishDate: "2026-01-15 10:00",
        premium: false,
        requiredRank: "all",
        author: "JUNKAN Documentary",
        views: 2400,
        thumbnail: "/images/documentary-1.jpg",
        duration: "48:32",
        authorBio: "JUNKANが制作するオリジナルドキュメンタリーシリーズ",
        tags: ["ドキュメンタリー", "地方創生", "限界集落"],
    },
    {
        id: "2",
        type: "video",
        title: "海が結ぶ未来 - 漁村とテクノロジーの融合",
        description: "伝統的な漁法とAI技術が交差する時、新たな観光資源が生まれる。瀬戸内海の小さな港町で起きている静かな革命。",
        status: "published",
        publishDate: "2025-12-20 10:00",
        premium: true,
        requiredRank: "gold",
        author: "JUNKAN Documentary",
        views: 1800,
        thumbnail: "/images/documentary-2.jpg",
        duration: "35:18",
        authorBio: "JUNKANが制作するオリジナルドキュメンタリーシリーズ",
        tags: ["ドキュメンタリー", "漁業", "AI"],
    },
    {
        id: "3",
        type: "article",
        title: "「関係人口」の設計図 - データが語る地方移住の新パターン",
        description: "統計データと現場の声から浮かび上がる、地方との新しい関わり方のモデルとは。全国200自治体のデータ分析。",
        status: "published",
        publishDate: "2026-02-07 09:00",
        premium: false,
        requiredRank: "all",
        author: "佐藤 雅人",
        views: 956,
        thumbnail: "/images/article-cover.jpg",
        tags: ["データ分析", "移住"],
        body: "（記事本文のモックデータ）...",
    },
    {
        id: "7",
        type: "external",
        title: "地方創生SDGsに取り組む企業事例集",
        status: "published",
        publishDate: "2026-01-28 14:00",
        premium: false,
        requiredRank: "all",
        author: "内閣府",
        views: 345,
        url: "https://www.chisou.go.jp/example",
        description: "地方創生SDGsに取り組む企業の優良事例を紹介するポータルサイト。",
    },
    // From Admin Content (Scheduled/Draft)
    {
        id: "4",
        type: "article",
        title: "温泉×ワーケーション：月商3000万を実現した旅館の戦略",
        status: "scheduled",
        publishDate: "2026-02-15 09:00",
        premium: true,
        requiredRank: "standard",
        author: "鈴木 理恵",
        views: 0,
        thumbnail: "/images/article-2.jpg",
        tags: ["ビジネス", "宿泊"],
    },
    {
        id: "5",
        type: "external",
        title: "総務省「関係人口創出事業」最新レポート 2026",
        status: "scheduled",
        publishDate: "2026-02-12 12:00",
        premium: false,
        requiredRank: "all",
        author: "総務省",
        views: 0,
        url: "https://www.soumu.go.jp/example",
        description: "地方創生に関する最新の統計データと政策方針をまとめた公式レポート。",
    },
    {
        id: "6",
        type: "article",
        title: "伝統工芸のDX：後継者不足を逆手に取ったブランド戦略",
        status: "draft",
        publishDate: "",
        premium: true,
        requiredRank: "platinum",
        author: "山田 健一",
        views: 0,
        thumbnail: "/images/documentary-1.jpg",
        tags: ["伝統工芸", "DX"],
    },
    // From Feed (Additional)
    {
        id: "art-4",
        type: "article",
        title: "農業×観光：体験型ツーリズムで年間来場者数5倍に",
        status: "published",
        publishDate: "2026-02-02 10:00", // 1 week ago
        premium: false,
        requiredRank: "all",
        author: "中村 美咲",
        views: 1200,
        thumbnail: "/Users/daimuwatanabe/.gemini/antigravity/brain/70ec0f9c-d1d0-4e4c-a3cf-3e9830d8cd3f/rural_japan_cover_1770638557750.png",
        tags: ["農業", "観光"],
    },
    {
        id: "art-5",
        type: "article",
        title: "地方発スタートアップが東京を超える日 - 3社の成功事例",
        status: "published",
        publishDate: "2026-01-26 10:00", // 2 weeks ago
        premium: true,
        requiredRank: "platinum",
        author: "高橋 翔太",
        views: 3100,
        thumbnail: "/images/article-cover.jpg",
        tags: ["スタートアップ", "事例"],
    },
    {
        id: "vid-4",
        type: "video",
        title: "古民家再生プロジェクト完全密着 - 築150年の家が蘇る",
        status: "published",
        publishDate: "2025-11-15 10:00",
        premium: false,
        requiredRank: "all",
        author: "JUNKAN Documentary",
        views: 3100,
        thumbnail: "/images/article-2.jpg",
        duration: "28:44",
    },
]

export const initialUserStats: UserStats = {
    totalUsers: 1024,
    activeRate: 73.2,
    monthlyNewUsers: 244,
    inviteConversionRate: 68.5,
}

export const initialGrowthData: GrowthData[] = [
    { month: "7月", total: 120, invited: 45 },
    { month: "8月", total: 185, invited: 72 },
    { month: "9月", total: 290, invited: 118 },
    { month: "10月", total: 410, invited: 165 },
    { month: "11月", total: 580, invited: 230 },
    { month: "12月", total: 780, invited: 310 },
    { month: "1月", total: 1024, invited: 420 },
]

export const initialWeeklyData: WeeklyRegistrationData[] = [
    { day: "月", registrations: 12 },
    { day: "火", registrations: 18 },
    { day: "水", registrations: 8 },
    { day: "木", registrations: 22 },
    { day: "金", registrations: 15 },
    { day: "土", registrations: 28 },
    { day: "日", registrations: 20 },
]

export const initialAdminUsers: AdminUser[] = [
    { id: "u1", name: "佐藤 雅人", email: "sato@example.com", referrals: 47, clicks: 312, registrations: 47, status: "active", joinDate: "2025-06-15" },
    { id: "u2", name: "鈴木 理恵", email: "suzuki@example.com", referrals: 38, clicks: 245, registrations: 38, status: "active", joinDate: "2025-07-02" },
    { id: "u3", name: "山田 健一", email: "yamada@example.com", referrals: 24, clicks: 156, registrations: 24, status: "active", joinDate: "2025-08-11" },
    { id: "u4", name: "田中 太郎", email: "tanaka@example.com", referrals: 24, clicks: 156, registrations: 24, status: "active", joinDate: "2025-08-20" },
    { id: "u5", name: "高橋 翔太", email: "takahashi@example.com", referrals: 15, clicks: 98, registrations: 15, status: "active", joinDate: "2025-09-03" },
    { id: "u6", name: "中村 美咲", email: "nakamura@example.com", referrals: 12, clicks: 78, registrations: 12, status: "pending", joinDate: "2025-10-15" },
    { id: "u7", name: "伊藤 裕子", email: "ito@example.com", referrals: 8, clicks: 52, registrations: 8, status: "active", joinDate: "2025-11-01" },
    { id: "u8", name: "渡辺 大輔", email: "watanabe@example.com", referrals: 5, clicks: 34, registrations: 5, status: "pending", joinDate: "2025-12-08" },
]

export const initialRewards: Reward[] = [
    { id: "r1", title: "Amazonギフトカード 5,000円", requiredReferrals: 5, description: "5名の招待完了で、Amazonギフトカードをプレゼント。", icon: "Gift", status: "active" },
    { id: "r2", title: "限定オンラインサロン招待", requiredReferrals: 10, description: "10名の招待完了で、クローズドなコミュニティへご招待します。", icon: "Users", status: "active" },
    { id: "r3", title: "オリジナルグッズ詰め合わせ", requiredReferrals: 20, description: "20名の招待完了で、JUNKAN限定グッズを製作してお届けします。", icon: "Package", status: "inactive" },
]

export const initialBroadcasts: Broadcast[] = [
    { id: "b1", title: "【重要】サービスメンテナンスのお知らせ", body: "2月20日 02:00〜05:00 の間、メンテナンスを実施します。", targetRank: "all", sentAt: "2026-02-05 10:00", status: "sent" },
    { id: "b2", title: "新コンテンツ公開・招待枠追加のお知らせ", body: "新しいドキュメンタリーを公開しました。あわせて招待枠を2つ追加しています。", targetRank: "platinum", sentAt: "2026-02-01 12:00", status: "sent" },
]
